# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cb8ac332b66873c8a305a5db3de55f528d1655e4f431d36dd3bcab557e5d186d63074fbd91616677668593199b899aae638e2ab0ed0d44c690533bed5b7255f

test:
  secret_key_base: 20a2478181a85bbfbf3dbb6bacadccaf74827d035d17f74c50238f5496f08f7c9f5f687778afc821ec9a279b6d0811b06b30dc276ac15770682b5ef9322beaf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
